<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="person" params="name size x y yaw=0 static=1 scale=1">
    <xacro:property name="model_scale" value="${1}"/>
    <xacro:property name="z_offset" value="${0}"/>
    <model name="person_standing">
      <link name="link">
        <inertial>
          <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} 0 -0  ${radians(yaw)}</pose>
          <mass>80</mass>
          <inertia>
            <ixx>24.879999999999999</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>25.73</iyy>
            <iyz>0</iyz>
            <izz>2.48</izz>
          </inertia>
        </inertial>
        <collision name="bottom">
          <pose>0 -0.1 0.01 0 0 0</pose>
          <geometry>
            <box>
              <size>0.5 0.35 0.02</size>
            </box>
          </geometry>
          <surface>
            <friction>
              <ode/>
            </friction>
            <bounce/>
            <contact/>
          </surface>
        </collision>
        <collision name="person">
          <pose>0 0 0.02 0.04 0 0</pose>
          <geometry>
            <mesh>
              <scale>${scale} ${ scale} ${ scale}</scale>
              <uri>model://person_standing/meshes/standing.dae</uri>
            </mesh>
          </geometry>
        </collision>
        <visual name="visual">
          <pose>0 0 0.02 0.04 0 0</pose>
          <geometry>
            <mesh>
              <scale>${scale} ${ scale} ${ scale}</scale>
              <uri>model://person_standing/meshes/standing.dae</uri>
            </mesh>
          </geometry>
        </visual>
        <pose>0 0 0 0 -0 0</pose>
        <enable_wind>false</enable_wind>
      </link>
      <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} 0 -0  ${radians(yaw)}</pose>
      <static>${static}</static>
      <self_collide>false</self_collide>
    </model>
  </xacro:macro>
  <xacro:macro name="includedModel" params="name type size x y yaw=0 static=1 scale=1">
    <model name="model_${name}">
      <xacro:property name="model_scale" value="${1}"/>
      <xacro:property name="z_offset" value="${0}"/>
      <static>${static}</static>
      <origin xyz="${size} ${y * size} 0"/>
      <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} 0 -0  ${radians(yaw)}</pose>
      <link name="link">
        <collision name="collision">
          <geometry>
            <mesh>
              <scale>${scale} ${ scale} ${ scale}</scale>
              <uri>model://person_standing/meshes/person_standing.obj</uri>
            </mesh>
          </geometry>
          <max_contacts>10</max_contacts>
          <surface>
            <contact>
              <ode/>
            </contact>
            <bounce/>
            <friction>
              <torsional>
                <ode/>
              </torsional>
              <ode/>
            </friction>
          </surface>
        </collision>
        <visual name="visual">
          <!-- <origin xyz="${x * size} ${y * size} 0"/> -->
          <geometry>
            <mesh>
              <scale>${size * model_scale * scale} ${size * model_scale * scale} ${size * model_scale * scale}</scale>
              <uri>model://person_standing/meshes/person_standing.obj</uri>
            </mesh>
          </geometry>
        </visual>
        <self_collide>0</self_collide>
        <enable_wind>0</enable_wind>
        <kinematic>0</kinematic>
      </link>
    </model>
  </xacro:macro>
  <xacro:macro name="includedState" params="name type size x y yaw=0 static=1 scale=1">
    <xacro:property name="model_scale" value="${1}"/>
    <xacro:property name="z_offset" value="${0}"/>
    <!-- START GENERATED SCALES AND OFFSETS-->
    <!-- END GENERATED -->
    <model name="model_${name}">
      <pose>${x * size} ${y * size}  ${z_offset*size * model_scale * scale + 0.01} 0 -0 ${radians(yaw)}</pose>
      <scale>${model_scale* size * scale} ${model_scale* size * scale} ${model_scale* size * scale}</scale>
      <link name="link">
        <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} 0 -0  ${radians(yaw)}</pose>
        <velocity>0 0 0 0 -0 0</velocity>
        <acceleration>0 0 0 0 -0 0</acceleration>
        <wrench>0 0 0 0 -0 0</wrench>
      </link>
    </model>
  </xacro:macro>
</robot>
