<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="tileWorld" params="name material size x y yaw=0 z_offset=0 model_scale=1 scale=1">
    <model name="unit_box_${name}">
      <model name="model_${name}">
        <static>1</static>
        <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} ${radians(90)} -0  ${radians(yaw)}</pose>
        <link name="link_${name}">
          <collision name="collision_${name}">
            <surface>
              <bounce>
                <restitution_coefficient>0.0</restitution_coefficient>
                <threshold>1000000.0</threshold>
              </bounce>
              <friction>
                <ode>
                  <mu>1</mu>
                  <mu2>1</mu2>
                </ode>
              </friction>
            </surface>
            <geometry>
              <mesh>
                <scale>${size * model_scale * scale} ${size * model_scale * scale} ${size * model_scale * scale}</scale>
                <!-- <scale>0.0254 0.0254 0.0254</scale> -->
                <uri>model://${material}/meshes/${material}.obj</uri>
              </mesh>
            </geometry>
          </collision>
          <visual name="visual_${name}">
            <geometry>
              <mesh>
                <pose>${x * size} ${y * size} ${z_offset*size * model_scale * scale + 0.01} ${radians(90)} -0  ${radians(yaw)}</pose>
                <scale>${size * model_scale * scale} ${size * model_scale * scale} ${size * model_scale * scale}</scale>
                <!-- <scale>0.0254 0.0254 0.0254</scale> -->
                <uri>model://${material}/meshes/${material}.obj</uri>
              </mesh>
            </geometry>
          </visual>
        </link>
      </model>
    </model>
  </xacro:macro>
  <xacro:macro name="tileState" params="name material size x y yaw=0">
    <model name="unit_box_${name}">
      <pose>${x * size} ${y * size} 0 -1e-05 -0 ${pi / 180 * yaw}</pose>
      <size>${size} ${size} 0.01</size>
      <link name="link">
        <pose>${x * size} ${y * size}  0 -1e-05 -0 ${pi / 180 * yaw}</pose>
        <velocity>0 0 0 0 -0 0</velocity>
        <acceleration>0.00 0.00 -9.78158 -0.00 0.0 1e-06</acceleration>
        <wrench>0.000 0.00 -9.78158 0 -0 0</wrench>
      </link>
    </model>
  </xacro:macro>
</robot>
